version: '3.8'
        
services: 
    API:
        image: node:16.15-slim
        build:
            context: ./
        command: node ./src/index.js
        environment:
            - SERVER_PORT=3000
            - TOKEN_SECRET=
            - WEB_API_KEY=
            - SERVICES_URL=
            - ADDRESS_SERVICE_PORT=8083
            - BILLING_SERVICE_PORT=8084
            - COUNTRY_SERVICE_PORT=8085
            - PAYPAL_SERVICE_PORT=8082
            - USER_SERVICE_PORT=8081
            - USERTYPE_SERVICE_PORT=8086
            - RESTAURANT_SERVICE_PORT=9081
            - PRODUCT_SERVICE_PORT=9082
            - MENU_SERVICE_PORT=9083
            - ORDER_SERVICE_PORT=9084
            - DELIVERY_SERVICE_PORT=9085
            - NOTIFICATION_SERVICE_PORT=9086
            - LOG_SERVICE_PORT=9087
            - PAYMENT_SERVICE_PORT=10081
            - STATS_SERVICE_PORT=10082
        ports:
            - 3000:3000
        deploy:
            restart_policy:
                condition: always